/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encuestadeusuario;
import java.awt.Color;
/**
 *
 * @author Juli
 */
public class FramePortabilidad extends javax.swing.JFrame {

    /**
     * Creates new form FramePortabilidad
     */
    public FramePortabilidad() {
        initComponents();
        setSize(600, 400);
        setLocationRelativeTo(null);
        setTitle("Encuesta de Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        adaptabilidadLabel = new javax.swing.JLabel();
        adaptCombo = new javax.swing.JComboBox<>();
        instalabilidadLabel = new javax.swing.JLabel();
        instalabCombo = new javax.swing.JComboBox<>();
        instalabilidadText = new javax.swing.JTextField();
        adaptabText = new javax.swing.JTextField();
        botonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel10.setText("Portabilidad");

        adaptabilidadLabel.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        adaptabilidadLabel.setText("Adaptabilidad");

        adaptCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "Compatible con 1 sistema operativo.", "Compatible con 2 sistemas operativos.", "Compatible con 3 o más sistemas operativos." }));
        adaptCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptComboActionPerformed(evt);
            }
        });

        instalabilidadLabel.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        instalabilidadLabel.setText("Instalabilidad");

        instalabCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "El producto se instala en 7 o más pasos.", "El producto se instala entre 4 y 6 pasos.", "El producto se instala en 3 o menos pasos." }));
        instalabCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instalabComboActionPerformed(evt);
            }
        });

        instalabilidadText.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        instalabilidadText.setForeground(new java.awt.Color(255, 255, 255));
        instalabilidadText.setEnabled(false);

        adaptabText.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        adaptabText.setForeground(new java.awt.Color(255, 255, 255));
        adaptabText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        adaptabText.setEnabled(false);

        botonSiguiente.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(adaptabilidadLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adaptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adaptabText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(instalabilidadLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(instalabCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instalabilidadText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adaptabilidadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adaptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaptabText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(instalabilidadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instalabCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instalabilidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adaptComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptComboActionPerformed
        switch(adaptCombo.getSelectedIndex()) {
            case 1: {
                adaptabText.setDisabledTextColor(Color.RED);
                adaptabText.setText("Evaluación: MALA");
                break;
            }
            case 2: {
                adaptabText.setDisabledTextColor(Color.orange);
                adaptabText.setText("Evaluación: REGULAR");
                break;
            }
            case 3: {
                adaptabText.setDisabledTextColor(Color.green);
                adaptabText.setText("Evaluación: BUENA");
                break;
            }
        }
    }//GEN-LAST:event_adaptComboActionPerformed

    private void instalabComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instalabComboActionPerformed
        switch(instalabCombo.getSelectedIndex()) {
            case 1: {
                instalabilidadText.setDisabledTextColor(Color.RED);
                instalabilidadText.setText("Evaluación: MALA");
                break;
            }
            case 2: {
                instalabilidadText.setDisabledTextColor(Color.orange);
                instalabilidadText.setText("Evaluación: REGULAR");
                break;
            }
            case 3: {
                instalabilidadText.setDisabledTextColor(Color.green);
                instalabilidadText.setText("Evaluación: BUENA");
                break;
            }
        }
    }//GEN-LAST:event_instalabComboActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        new FrameFinal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePortabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePortabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePortabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePortabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePortabilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adaptCombo;
    private javax.swing.JTextField adaptabText;
    private javax.swing.JLabel adaptabilidadLabel;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JComboBox<String> instalabCombo;
    private javax.swing.JLabel instalabilidadLabel;
    private javax.swing.JTextField instalabilidadText;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
