/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encuestadeusuario;
import java.awt.Color;
/**
 *
 * @author Juli
 */
public class FrameEficiencia extends javax.swing.JFrame {

    /**
     * Creates new form FrameEficiencia
     */
    public FrameEficiencia() {
        initComponents();
        setSize(600, 400);
        setLocationRelativeTo(null);
        setTitle("Encuesta de Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evalEficienciaLabel = new javax.swing.JLabel();
        usoProcLabel = new javax.swing.JLabel();
        usoProcesadorCombo = new javax.swing.JComboBox<>();
        eficienciaText2 = new javax.swing.JTextField();
        tiempoCombo = new javax.swing.JComboBox<>();
        compTiempoLabel = new javax.swing.JLabel();
        eficienciaText1 = new javax.swing.JTextField();
        botonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(507, 304));

        evalEficienciaLabel.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        evalEficienciaLabel.setText("Eficiencia");

        usoProcLabel.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        usoProcLabel.setText("Uso de Procesador");

        usoProcesadorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "41% o más de uso de procesador.", "11% a 40% de uso de procesador.", "10% o menos de uso de procesador." }));
        usoProcesadorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usoProcesadorComboActionPerformed(evt);
            }
        });

        eficienciaText2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        eficienciaText2.setForeground(new java.awt.Color(255, 255, 255));
        eficienciaText2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        eficienciaText2.setEnabled(false);

        tiempoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "El producto está 5 o más segundos sin informar al usuario del estado de la solicitud.", "El producto está entre 2 y 4 segundos sin informar al usuario del estado de la solicitud.", "El producto está menos de 1 segundo sin informar al usuario del estado de la solicitud." }));
        tiempoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoComboActionPerformed(evt);
            }
        });

        compTiempoLabel.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        compTiempoLabel.setText("Comportamiento en el tiempo");

        eficienciaText1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        eficienciaText1.setForeground(new java.awt.Color(255, 255, 255));
        eficienciaText1.setEnabled(false);

        botonSiguiente.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usoProcesadorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eficienciaText2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(evalEficienciaLabel)
                            .addComponent(usoProcLabel)
                            .addComponent(compTiempoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tiempoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eficienciaText1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evalEficienciaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usoProcLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usoProcesadorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eficienciaText2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(compTiempoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eficienciaText1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usoProcesadorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usoProcesadorComboActionPerformed
        switch(usoProcesadorCombo.getSelectedIndex()) {
            case 1: {
                eficienciaText2.setDisabledTextColor(Color.RED);
                eficienciaText2.setText("MALA");
                break;
            }
            case 2: {
                eficienciaText2.setDisabledTextColor(Color.orange);
                eficienciaText2.setText("REGULAR");
                break;
            }
            case 3: {
                eficienciaText2.setDisabledTextColor(new java.awt.Color(51, 153, 51));
                eficienciaText2.setText("BUENA");
                break;
            }
        }
    }//GEN-LAST:event_usoProcesadorComboActionPerformed

    private void tiempoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoComboActionPerformed
        switch(tiempoCombo.getSelectedIndex()) {
            case 1: {
                eficienciaText1.setDisabledTextColor(Color.RED);
                eficienciaText1.setText("MALA");
                break;
            }
            case 2: {
                eficienciaText1.setDisabledTextColor(Color.orange);
                eficienciaText1.setText("REGULAR");
                break;
            }
            case 3: {
                eficienciaText1.setDisabledTextColor(new java.awt.Color(51, 153, 51));
                eficienciaText1.setText("BUENA");
                break;
            }
        }
    }//GEN-LAST:event_tiempoComboActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        new FrameFiabilidad().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEficiencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel compTiempoLabel;
    private javax.swing.JTextField eficienciaText1;
    private javax.swing.JTextField eficienciaText2;
    private javax.swing.JLabel evalEficienciaLabel;
    private javax.swing.JComboBox<String> tiempoCombo;
    private javax.swing.JLabel usoProcLabel;
    private javax.swing.JComboBox<String> usoProcesadorCombo;
    // End of variables declaration//GEN-END:variables
}
