/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package encuestadeusuario;

import java.awt.Color;

/**
 *
 * @author Juli
 */
public class FrameFuncionabilidad extends javax.swing.JFrame {

    /**
     * Creates new form FrameFuncionabilidad
     */
    public FrameFuncionabilidad() {
        initComponents();
        setSize(600, 400);
        setLocationRelativeTo(null);
        setTitle("Encuesta de Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evalFuncText = new javax.swing.JLabel();
        segAccesoText = new javax.swing.JLabel();
        pregunta1Text = new javax.swing.JLabel();
        pregunta2Text = new javax.swing.JLabel();
        seguridadAccesoCombo = new javax.swing.JComboBox<>();
        exactitudCombo = new javax.swing.JComboBox<>();
        exactitudText = new javax.swing.JTextField();
        seguridadText = new javax.swing.JTextField();
        botonSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        evalFuncText.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        evalFuncText.setText("Funcionabilidad");

        segAccesoText.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        segAccesoText.setText("Seguridad de Acceso");

        pregunta1Text.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        pregunta1Text.setText("¿El Software posee encriptación de datos?");

        pregunta2Text.setFont(new java.awt.Font("Gill Sans MT", 2, 12)); // NOI18N
        pregunta2Text.setText("¿El Software posee inicio de sesión de usuarios?");

        seguridadAccesoCombo.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        seguridadAccesoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "No cumple con alguna característica.", "Cumple con 1 característica.", "Cumple con 2 características." }));
        seguridadAccesoCombo.setAutoscrolls(true);
        seguridadAccesoCombo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seguridadAccesoCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seguridadAccesoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguridadAccesoComboActionPerformed(evt);
            }
        });

        exactitudCombo.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        exactitudCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción...", "Los resultados tienen un error del orden de 10^-3 o superior.", "Los resultados tienen un error del orden entre10^-4 y 10^-6.", "Los resultados tienen un error del orden de10^-7 o inferior." }));
        exactitudCombo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exactitudCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exactitudComboActionPerformed(evt);
            }
        });

        exactitudText.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        exactitudText.setForeground(new java.awt.Color(240, 240, 240));
        exactitudText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exactitudText.setEnabled(false);

        seguridadText.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        seguridadText.setForeground(new java.awt.Color(240, 240, 240));
        seguridadText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        seguridadText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        seguridadText.setEnabled(false);
        seguridadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguridadTextActionPerformed(evt);
            }
        });

        botonSiguiente.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel1.setText("Evaluación:");

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel2.setText("Evaluación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(evalFuncText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segAccesoText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pregunta1Text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pregunta2Text, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seguridadAccesoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(seguridadText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(exactitudCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                    .addComponent(exactitudText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evalFuncText)
                .addGap(18, 18, 18)
                .addComponent(segAccesoText)
                .addGap(18, 18, 18)
                .addComponent(pregunta1Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pregunta2Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seguridadAccesoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seguridadText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exactitudCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exactitudText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seguridadAccesoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguridadAccesoComboActionPerformed
        switch(seguridadAccesoCombo.getSelectedIndex()) {
            case 1: {
                seguridadText.setDisabledTextColor(Color.RED);
                seguridadText.setText("MALA");
                break;
            }
            case 2: {
                seguridadText.setDisabledTextColor(Color.orange);
                seguridadText.setText("REGULAR");
                break;
            }
            case 3: {
                seguridadText.setDisabledTextColor(new java.awt.Color(51, 153, 51));
                seguridadText.setText("BUENA");
                break;
            }

        }
    }//GEN-LAST:event_seguridadAccesoComboActionPerformed

    private void exactitudComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exactitudComboActionPerformed
        switch(exactitudCombo.getSelectedIndex()) {
            case 1: {
                exactitudText.setDisabledTextColor(Color.RED);
                exactitudText.setText("MALA");
                break;
            }
            case 2: {
                exactitudText.setDisabledTextColor(Color.orange);
                exactitudText.setText("REGULAR");
                break;
            }
            case 3: {
                exactitudText.setDisabledTextColor(new java.awt.Color(51, 153, 51));
                exactitudText.setText("BUENA");
                break;
            }
        }
    }//GEN-LAST:event_exactitudComboActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        new FrameEficiencia().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void seguridadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguridadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seguridadTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFuncionabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFuncionabilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel evalFuncText;
    private javax.swing.JComboBox<String> exactitudCombo;
    private javax.swing.JTextField exactitudText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pregunta1Text;
    private javax.swing.JLabel pregunta2Text;
    private javax.swing.JLabel segAccesoText;
    private javax.swing.JComboBox<String> seguridadAccesoCombo;
    private javax.swing.JTextField seguridadText;
    // End of variables declaration//GEN-END:variables
}
